function [smoother,fitresult, gof] = blazeCorrection(finalSpecIn,finalWave,pp)
%CREATEFIT(X,FINALSPEC)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : x
%      Y Output: finalSpec
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 19-Sep-2014 17:16:06

finalSpec=finalSpecIn;

xx=1:length(finalSpec);
x=xx;

mask=finalWave>654 & finalWave<658;
mask=mask | finalWave>686 & finalWave<697;
mask=mask | finalWave>716 & finalWave<722;
mask=mask | finalWave>722 & finalWave<733;

p=0.05;
ignore=1./finalSpec > p | mask;
x(ignore)=[];
finalSpec(ignore)=[];
smoother=csaps(x,finalSpec,1e-10,xx);


p=1.05;
finalSpec=finalSpecIn;
x=xx;
ignore=1./(finalSpec./smoother) > p | mask;
x(ignore)=[];
finalSpec(ignore)=[];

%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( x, finalSpec );

% Set up fittype and options.
ft = fittype( 'smoothingspline' );
opts = fitoptions( 'Method', 'SmoothingSpline' );
opts.Normalize = 'on';
opts.SmoothingParam = pp;

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

smoother=feval(fitresult,xx);


